### PR TITLE
Update to work with bevy main (and eventually 0.8)

### PR DESCRIPTION
**Pull request by DGriffin91**
This needs a more thorough review. But it looks like the examples are working, and it's working in at least one of my projects.

### CODE REVIEW

**Comment by zimond** [comment]
This is broken as [bevy#4402](https://github.com/bevyengine/bevy/pull/4402) landed

**Comment by DGriffin91** [comment]
Just messed with it a bit and it seems like this will require a bit of a more significant re-work now as the extract systems currently require mutable access to resources in the main world.

**Comment by zimond** [comment]
Yes and use immutable `Res` with clone could make the examples run, but with only a black screen [code](https://github.com/zimond/bevy_egui/commit/65d8cd9e22dc534612e3436d09388b362c3addbe) I didn't have the time to dig in

**Comment by DGriffin91** [comment]
@[zimond](https://github.com/zimond) I tried using the clone with `egui_render_output` in the extract instead of take and it looks like it's working for me. I would assume the clone here is less efficient than take, but I'm not sure if it's enough slower to matter.

**Comment by zimond** [comment]
I think some clones won't hurt the perf that much

**Comment by mvlabat** [comment]
Hi! Thank you for the PR! I think cloning is fine for now. Maybe, if we see an issue with performance, we might want to wrap it into a `Mutex`, if copying a lot of bytes around will become more expensive than dealing with locking.
I've also pushed a small commit to refactor the example, to make the error of initialization more visible (it panic now if we forget to initialize the camera properly, instead of making it silent) and fix the linters.

**Comment by zimond** [comment]
Closing a window on this branch emits panic:

```rust
let extracted_window = &world.get_resource::<ExtractedWindows>().unwrap().windows[&self.window_id];
```

```bash
thread 'main' panicked at 'no entry found for key' egui_node.rs:328:14
```

**Comment by DGriffin91** [comment]
Hmm, I tried this
```rust
        let extracted_windows = &world.get_resource::<ExtractedWindows>().unwrap().windows;

        let extracted_window =
            if let Some(extracted_window) = extracted_windows.get(&self.window_id) {
                extracted_window
            } else {
                return Ok(());
            };
 ```
But now when I close the window the app continues to run with the window closed and says:
```
2022-07-18T16:59:55.466789Z  INFO bevy_winit: Skipped event for closed window: WindowId(00000000-0000-0000-0000-000000000000)
2022-07-18T16:59:55.467187Z  INFO bevy_winit: Skipped event for closed window: WindowId(00000000-0000-0000-0000-000000000000)
2022-07-18T16:59:55.470299Z  INFO bevy_winit: Skipped event for closed window: WindowId(00000000-0000-0000-0000-000000000000)
```

**Comment by mvlabat** [comment]
Any chance that this is an issue on the Bevy's end? Not really sure what can cause this in `bevy_egui` itself. 
I haven't got a chance to look into it myself, but does it happen with every example? Or is it specific to the multiple windows example?

If it happens in every example, I'd suggest to try to reproduce it in a clean Bevy project. And if it reproduces there without `bevy_egui`, we need to file an issue in their repo.

**Comment by DGriffin91** [comment]
@mvlabat It appears that it is indeed an issue with bevy: https://github.com/bevyengine/bevy/issues/5384

**Comment by CGMossa** [comment]
Is this issue blocking this PR or has it been fixed?

**Comment by mvlabat** [comment]
Definitely not a blocker for us. I don't know if it has been fixed in Bevy's main, but we'll merge this PR regardless once 0.8 is released

**Comment by philpax** [comment]
Bevy 0.8's now out - I've just built this fork with it (opened a PR for it here https://github.com/DGriffin91/bevy_egui/pull/2) and everything seems to work fine 👍

**Comment by mvlabat** [comment]
Thank you for your help with the update! I'll release it soon

**Pull request merged**
