### PR TITLE
update to bevy 0.6

### PR DESCRIPTION
**Pull request by jakobhellermann**
Opening this to avoid duplicated work in case someone else wants to use `bevy_egui` with bevy main.

### CODE REVIEW

**Comment by OfficialURL** [comment]
Currently, trying to use this branch gives me the error that "the trait bound `EguiPlugin: bevy::prelude::Plugin` is not satisfied."

**Comment by jakobhellermann** [comment]
> This: [jakobhellermann#1](https://github.com/jakobhellermann/bevy_egui/pull/1) fixes that error.

Thanks!

**Comment by tbarusseau** [comment]
Thanks for putting up the branch!

Even with [this modification (using the latest version of the branch `bevy-main`)](https://github.com/jakobhellermann/bevy_egui/pull/1), I'm getting this same error: `the trait 'bevy::prelude::Plugin' is not implemented for 'EguiPlugin'`.

Any idea why?

**Comment by aevyrie** [comment]
> Thanks for putting up the branch!
> 
> Even with [this modification (using the latest version of the branch `bevy-main`)](https://github.com/jakobhellermann/bevy_egui/pull/1), I'm getting this same error: `the trait 'bevy::prelude::Plugin' is not implemented for 'EguiPlugin'`.
> 
> Any idea why?

I just tested after updating main, with no issue. That error means the Plugin types are not equivalent (from different upstream versions). I'd suggest a cargo clean and cargo update. Also double check you are using the bevy main branch from github.

**Comment by tbarusseau** [comment]
Duh, turns out that I didn't specify `branch = main` in my `Cargo.toml`, and even though I thought I thoroughly checked that the commit of the git repositories used were the same... I was wrong!

Thanks for the sanity check aevyrie, and thanks jakobhellermann for the PR.

**Comment by OfficialURL** [comment]
I've made my own fork of this that also updates `egui` to 0.13.0: https://github.com/OfficialURL/bevy_egui/tree/bevy-main

**Comment by CGMossa** [comment]
I don't know how this is going, but I see that for example `AppBuilder` has been removed, so this needs to be updated here. Is it in this PR you'd do it?

**Comment by jakobhellermann** [comment]
@CGMossa I rebased the branch, it should work now.

**Comment by CGMossa** [comment]
Thanks.

I didn't know how to do it in a better way. Please close this if you like.

**Comment by OfficialURL** [comment]
This branch does not currently work. It seems to want a bunch of lifetime arguments.

**Comment by OfficialURL** [comment]
I've submitted a PR to make this work in the latest Bevy commit.

**Comment by OfficialURL** [comment]
I've bumped my branch to egui 0.14, in case anyone is interested.

**Comment by mvlabat** [comment]
I've just published bevy_egui 0.7.0 upgrading egui to 0.14.

**Comment by korczis** [comment]
Nice! Thanks for sharing. I was about ask if somebody works on this and if can summarize steps needed to achieve this?

So, please, can you write up some summary of steps needed to achieve this? Some details will be great. 

I want to jump on it as soon as possible and help with it.

Thanks in advance.

**Comment by mvlabat** [comment]
@jakobhellermann you can remove this line to make the build green again: https://github.com/mvlabat/bevy_egui/blob/80541c73719ca14d9683ced0f1c9f15cf8985007/.github/workflows/check.yml#L107

It's a workaround needed for Bevy 0.5.

**Comment by Shatur** [comment]
0.6 was released!

**Comment by jakobhellermann** [comment]
I'll fix the two window example and mark the PR as ready to review :+1:

**Comment by mvlabat** [comment]
Just tested it, works great (in WASM as well)! Thanks so much for your work @jakobhellermann, I can't imagine following all the Bevy changes myself. @aevyrie, @TheRawMeatball, thank you for your contributions as well.

Preparing the release!

**Pull request merged**
