### PR TITLE
Add headless mode support

### PR DESCRIPTION
**Pull request by Shatur**
I implemented support for [headless mode](https://github.com/bevyengine/bevy/pull/3439) that now available in 0.6. I just basically removed some unwraps.
This makes it easier to test systems that use egui.

### CODE REVIEW

**Comment by mvlabat** [comment]
Looks great! Thank you for the PR

**Comment by Shatur** [comment]
@mvlabat could you draft a new release with this feature?

**Comment by mvlabat** [comment]
@Shatur sure. I'll try to do it today or tomorrow, just want to batch a couple of other fixes into it as well

**Comment by mvlabat** [comment]
0.10.1 has been released

**Pull request merged**
