### PR TITLE
Directly use EventReader

### PR DESCRIPTION
**Pull request by Weasy666**
Use EventReader directly, which was made possible by https://github.com/bevyengine/bevy/pull/1244.

This should not be merged before the release of Bevy 0.5, as it needs at least commit https://github.com/bevyengine/bevy/commit/a880b5450829411b0248e47cc066915234371d86 to work.

One test is failing, but i am not sure if it has something to do with my changes. I tested this in one of my project and it works just fine.

```
running 2 tests
test src\lib.rs - EguiSettings::scale_factor (line 100) ... ok
test src\lib.rs - (line 23) ... FAILED

failures:

---- src\lib.rs - (line 23) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'Compute Task Pool (2)' panicked at 'assertion failed: pixels_per_point > 0.0', C:\Users\...\.cargo\registry\src\github.com-1ecc6299db9ec823\epaint-0.8.0\src\text\font.rs:76:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', C:\Users\...\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\task.rs:368:45



failures:
    src\lib.rs - (line 23)

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.15s
```

### CODE REVIEW

**Comment by mvlabat** [comment]
Hi! Thanks for the PR. That's an awesome change, looking forward to Bevy 0.5 now. :) I suggest we merge it once the release lands.

Yeah, I've just realized that one of my documentation tests is failing. I'll look into it, probably I should just mark it with the `no_run` directive. Since this crate doesn't have any real tests, I didn't even bother with running `cargo test` before, lol.

**Comment by jakobhellermann** [comment]
Could this maybe be merged into a `bevy-0.5` branch or similar? For [bevy-inspector-egui](https://github.com/jakobhellermann/bevy-inspector-egui) I'd like to temporarily depend on the master version of bevy and therefore of bevy-egui.

**Comment by mvlabat** [comment]
@jakobhellermann done. Though I can't promise I'll actively maintain that branch until 0.5 actually lands, but feel free to send me PRs. I guess another option would be depending on a fork.

**Comment by jakobhellermann** [comment]
Thanks, I'll send PRs whenever stuff breaks :+1:

**Comment by mvlabat** [comment]
Merged as a part of #12. Thank you for the PR!

**Comment by Weasy666** [comment]
You are welcome! 😃

**Pull request closed without merging**
