### PR TITLE
Paint callback functionality improvements

### PR DESCRIPTION
**Pull request by PPakalns**
Support executing additional render passes or adding command buffers from paint callback

### CODE REVIEW

**Comment by mvlabat** [comment]
Hi, thanks for the PR!

Recently, we've also added this node: https://github.com/mvlabat/bevy_egui/blob/3aed12f9292d46c81a1cde1160198c6fb572e253/src/egui_render_to_texture_node.rs

It duplicates probably ~80% of `egui_node.rs` code, which I'm not a fan of. But until we refactor that, we'll have to introduce any changes to both of them.

**Comment by PPakalns** [comment]
Logic added, feel free to edit branch if minor fixes are needed.

**Comment by PPakalns** [comment]
Ping in case of missing this in github feed :)

**Comment by mvlabat** [comment]
Looks great, thank you!

**Pull request merged**
