### PR TITLE
Update to Egui 0.18

### PR DESCRIPTION
**Pull request by mvlabat**

### CODE REVIEW

**Comment by justacec** [comment]
Know what I am doing tonight...  Thanks for this gem.  :)

**Comment by gilescope** [comment]
Something odd seems to be going on. Did egui 0.18 get pulled or something? For some reason cargo seems really keen on not using that version...

error: failed to select a version for the requirement `egui = "^0.18"`
candidate versions found which didn't match: 0.17.0, 0.16.1, 0.16.0, ...

Something fishy is going on...

**Comment by mvlabat** [comment]
Hey @gilescope! Not sure what can be the reason for this... Can you try deleting you `~/.cargo/registry` and try to build your project again?
If it's open source and you can send me a link, I'll take a look.

**Comment by kuriho** [comment]
@gilescope @mvlabat ran into the same issue. `cargo clean` didn't have any effect but a long over due `rustup update` solved this for me.

**Pull request merged**
