### PR TITLE
Multiple windows support

### PR DESCRIPTION
**Pull request by mvlabat**
Based on #13 

Issues to fix:
- [x] When a new window is spawned, it acquires the focus, at least on Windows (TODO: test other platforms), but the active context is still the default window. That results in events coming from the second window being consumed by the default context.
- [x] Clipboard can paste into several fields at the same time if they are all active in different windows.

### CODE REVIEW

**Comment by mvlabat** [comment]
@jakobhellermann I've extended the two windows example a bit and found a couple of minor bugs. I'm looking into them right now, but if you already have an idea on how to fix those, that will help. :)

**Comment by jakobhellermann** [comment]
> @jakobhellermann I've extended the two windows example a bit and found a couple of minor bugs. I'm looking into them right now, but if you already have an idea on how to fix those, that will help. :)

What bugs are there? Running locally seems to work for me.

**Comment by mvlabat** [comment]
@jakobhellermann sorry, I forgot to mention that I've described them in the PR body. :) The clipboard issue is now fixed, now I'm trying to figure out what to do with the invalid initial focus.

**Comment by jakobhellermann** [comment]
On linux the focus doesn't seem to be an issue. The second window gets focused as well, but tab presses etc. get correctly handled in the second window.

**Comment by mvlabat** [comment]
Yeah, it looks Windows specific... I wasn't able to reproduce it on my Macbook either.

**Pull request merged**
