### PR TITLE
Settings required for dynamic builds on egui

### PR DESCRIPTION
**Pull request by bayswaterpc**
This adds required file and dependency adjustment for bevy/dynamic Fast Compile started with issue https://github.com/mvlabat/bevy_egui/issues/22 , 

Also adds example targets in the toml, 1 less thing for beginners to have to figure out.

### CODE REVIEW

**Comment by mvlabat** [comment]
Hi! Thanks for the PR.
I have a question: are you sure that these changes are needed to be able to compile an application with dynamic linking? I'm afraid that it'll force dynamic linking for all bevy_egui users, regardless of whether they want it or not. I believe it shouldn't be done it the library itself.

**Comment by bayswaterpc** [comment]
Yes that would have, I meant to remove the "dyanmic"  in the dependencies & leave a commented out so it should have been.  

```
[dependencies]
bevy = { version = "0.5", default-features = false, features = ["render", "bevy_winit"] }
#use dynamic for  Fast Compile dependencies required , https://bevyengine.org/learn/book/getting-started/setup/
#bevy = { version = "0.5", default-features = false, features = ["bevy_wgpu", "x11", "png", "dynamic"] }
egui = "0.11.0"
webbrowser = { version = "0.5.5", optional = true }
winit = { version = "0.24.0", features = ["x11"], default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clipboard = { version = "0.5.0", optional = true }
thread_local = { version = "1.1.0", optional = true }

[dev-dependencies]
version-sync = "0.9.2"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
bevy = { version = "0.5", default-features = false, features = ["bevy_wgpu", "x11", "png"] }
#use dynamic for  Fast Compile dependencies required , https://bevyengine.org/learn/book/getting-started/setup/
#bevy = { version = "0.5", default-features = false, features = ["bevy_wgpu", "x11", "png", "dynamic"] }
```

From my experience with the bug, the difference between building and not building was the inclusion of the "dynamic" dependency.  So  I don't think it will build dynamically with that removed.  However the config.toml could be causing some side effect which I'm not fully aware of.  I'll post on the bevy thread where I got my fix to check https://github.com/bevyengine/bevy/pull/2016.

**Comment by mvlabat** [comment]
Sorry, I'm still convinced that this shouldn't be a part of the library. The faster build config also implies that every contributor has to have another linker installed. If they don't, they'll have a pretty confusing error in their console. All that can be documented in the README of course, but I believe that it's too much hassle for too little benefit. 

If a user wants to use faster builds for every project by default, they can still do that via environment variables. I see this config much more useful for applications, where developers spend most of their time while iterating on them.

I'll close this PR. But feel free to leave additional comments here if you have any. If more developers will show interest in this, I might reconsider it as well.

**Comment by bayswaterpc** [comment]
That makes sense. My main goal was to spare someone else the pain of having
to figure out the windows dynamic build configuration on their project.
The pr and closed issue should pop up for those searching so mission
accomplished.  Thanks for your consideration and work on this!

**Pull request closed without merging**
