### PR TITLE
Window is open and checkbox is checked added to ui.rs example

### PR DESCRIPTION
**Pull request by tomuxmon**
Added demonstration how to use `egui::Window::open(self, &'open mut bool)`. Since I am a newcomer to rust I have been struggling with passing a mutable bool. Should be useful for other newcomers as well since closing or opening a window is such a common use case.

Hope that helps.

### CODE REVIEW

**Comment by tomuxmon** [comment]
Yes, it can. But then the default state will be a closed window unless we provide a manual Default implementation for `UiState`. Is there a way to make `is_open` default to true and leave `#[derive(Default)]` on `UiState`?

**Comment by tomuxmon** [comment]
Using only `UiState` now. Left default as is but introduced `configure_ui_state` startup function to set `is_window_open` to `true`.

**Comment by tomuxmon** [comment]
can we merge it or is there something else to be fixed?

**Comment by mvlabat** [comment]
Merged. Thank you!

**Pull request merged**
